### ISSUE TITLE
Docker & Deployment

### ISSUE THREAD

**Issue by BlobbyBob** [IoTineSalt/eyeotine#3]
Since the server software is splitted into modules, a deployment using containers (eg. Docker) should be well suited.

How would the architecture of this look and how could integrate this into a good build system?

**Comment by jogehl** [comment]
## Advantages for using docker:
- simple start up and shutdown of modules. The start can be also done with a shell script but the possibility of a simple shutdown is of great usage
- connections between the modules can be defined for all possible environment so there is dependency if it is used in different environments
- simple version control and simple distribution as a docker image
- if we decide to use mqqt it is simple to set up the broker and all the connections #6 
- possible use of GUI with docker
- easy testing using automated tests 

## Disadvantages
- to use the implementation one has to install docker
- use of docker not easy for users with no technical knowledge

## Possible Architecture
- Visualization #8  
- Tracker 
- Mqqt Broker
- Serverside API for ESPs.
