### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by BlobbyBob** [IoTineSalt/eyeotine#6]
We decided to use MQTT as a protocol for communication between modules on the central server.

What MQTT broker should we use and why? We also need some more information, what MQTT is capable of and how we should structure our internal APIs.

**Comment by janphilg** [comment]
This site gives a first overview of MQTT broker and client-side libraries.

[https://mqtt.org/software/#servers-brokers](url)

**Comment by janphilg** [comment]
[Mosquitto](https://www.mosquitto.org/)

[Official image for Docker](https://hub.docker.com/_/eclipse-mosquitto)

**Comment by janphilg** [comment]
Client:

[](https://github.com/eclipse/paho.mqtt.python)

**Comment by janphilg** [comment]
[Paho documentation](https://www.eclipse.org/paho/index.php?page=clients/python/docs/index.php)
